### ISSUE TITLE
Login credentials

### ISSUE THREAD

**Issue by megharajdeepak** [sickelap/ng-starter#1]
Hi,
Thanks for this starter, its awesome :)
By the way, I couldn't find the login credentials for the demo:
https://sickelap.github.io/ng-starter/

**Comment by sickelap** [comment]
Ah yes, I perhaps should include the text of some sort on the login screen explaining that.
Anyway, the email is anything that resembles a valid email and password anything min length is 8.
Relevant files are: https://github.com/sickelap/ng-starter/blob/master/src/shared/services/auth.service.ts and https://github.com/sickelap/ng-starter/blob/master/src/modules/%2Bauth/components/login-form.component.ts

**Comment by sickelap** [comment]
updated readme with login info
